using System.Data.Entity;
using PALMS.Data.Objects.ClientModel;
using PALMS.Data.Objects.LinenModel;

namespace PALMS.Data.Services
{
    public class ContextInitializer : CreateDatabaseIfNotExists<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            //AddFamilyLinen(context);
            AddGroupLinen(context);
            //AddMasterLinen(context);
            //AddPrimeInfo(context);
            context.SaveChanges();
        }

        private void AddGroupLinen(DataContext context)
        {
            var groupLinen = context.GroupLinens;

            groupLinen.Add(new GroupLinen { Name = "Group 1" });
        }

        private void AddFamilyLinen(DataContext context)
        {
            var familyLinen = context.FamilyLinens;

            //familyLinen.Add(new FamilyLinen { Name = "Shirt" });

            familyLinen.Add(new FamilyLinen { Name = "ABAYA" });
            familyLinen.Add(new FamilyLinen { Name = "APPLICATOR" });
            familyLinen.Add(new FamilyLinen { Name = "APRON" });
            familyLinen.Add(new FamilyLinen { Name = "ARM REST" });
            familyLinen.Add(new FamilyLinen { Name = "BACK COVER" });
            familyLinen.Add(new FamilyLinen { Name = "BACK REST" });
            familyLinen.Add(new FamilyLinen { Name = "BACK SUPPORT" });
            familyLinen.Add(new FamilyLinen { Name = "BAG" });
            familyLinen.Add(new FamilyLinen { Name = "BANDANA" });
            familyLinen.Add(new FamilyLinen { Name = "BATH MAT" });
            familyLinen.Add(new FamilyLinen { Name = "BATH ROBE" });
            familyLinen.Add(new FamilyLinen { Name = "BATH RUG" });
            familyLinen.Add(new FamilyLinen { Name = "BATH SHEET " });
            familyLinen.Add(new FamilyLinen { Name = "BATH TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "BED" });
            familyLinen.Add(new FamilyLinen { Name = "BED COVER" });
            familyLinen.Add(new FamilyLinen { Name = "BED LINER" });
            familyLinen.Add(new FamilyLinen { Name = "BED RUNNER" });
            familyLinen.Add(new FamilyLinen { Name = "BED SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "BED SPREAD" });
            familyLinen.Add(new FamilyLinen { Name = "BED THROW " });
            familyLinen.Add(new FamilyLinen { Name = "BEDDING" });
            familyLinen.Add(new FamilyLinen { Name = "BELT" });
            familyLinen.Add(new FamilyLinen { Name = "BIDET TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "BLANKET" });
            familyLinen.Add(new FamilyLinen { Name = "BLOUSE" });
            familyLinen.Add(new FamilyLinen { Name = "BOTTOM SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "BOW TIE" });
            familyLinen.Add(new FamilyLinen { Name = "BRASSIERE" });
            familyLinen.Add(new FamilyLinen { Name = "BREAD BASKET" });
            familyLinen.Add(new FamilyLinen { Name = "BREAD COVER" });
            familyLinen.Add(new FamilyLinen { Name = "CAP" });
            familyLinen.Add(new FamilyLinen { Name = "CARPET" });
            familyLinen.Add(new FamilyLinen { Name = "CHAIR" });
            familyLinen.Add(new FamilyLinen { Name = "CHEST COVER" });
            familyLinen.Add(new FamilyLinen { Name = "CHEST SUPPORT" });
            familyLinen.Add(new FamilyLinen { Name = "CLOTH" });
            familyLinen.Add(new FamilyLinen { Name = "COASTER" });
            familyLinen.Add(new FamilyLinen { Name = "COAT" });
            familyLinen.Add(new FamilyLinen { Name = "COMFORTER" });
            familyLinen.Add(new FamilyLinen { Name = "COSTUME" });
            familyLinen.Add(new FamilyLinen { Name = "COVERALL" });
            familyLinen.Add(new FamilyLinen { Name = "CURTAIN" });
            familyLinen.Add(new FamilyLinen { Name = "CUSHION" });
            familyLinen.Add(new FamilyLinen { Name = "DRESS" });
            familyLinen.Add(new FamilyLinen { Name = "DUSTER" });
            familyLinen.Add(new FamilyLinen { Name = "DUVET" });
            familyLinen.Add(new FamilyLinen { Name = "DUVET COVER" });
            familyLinen.Add(new FamilyLinen { Name = "EQUIPMENT COVER" });
            familyLinen.Add(new FamilyLinen { Name = "FACE MASK" });
            familyLinen.Add(new FamilyLinen { Name = "FACE TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "FITTED SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "FLAG" });
            familyLinen.Add(new FamilyLinen { Name = "FLAT LINENS" });
            familyLinen.Add(new FamilyLinen { Name = "FOAM BACK" });
            familyLinen.Add(new FamilyLinen { Name = "FOAM COVER" });
            familyLinen.Add(new FamilyLinen { Name = "FOOT COVER" });
            familyLinen.Add(new FamilyLinen { Name = "FOOT SUPPORTER" });
            familyLinen.Add(new FamilyLinen { Name = "FWALA COVER" });
            familyLinen.Add(new FamilyLinen { Name = "GLASS BRUSH" });
            familyLinen.Add(new FamilyLinen { Name = "GLOVES" });
            familyLinen.Add(new FamilyLinen { Name = "GOWN" });
            familyLinen.Add(new FamilyLinen { Name = "GUTRA" });
            familyLinen.Add(new FamilyLinen { Name = "GUTRA & KHAFIA" });
            familyLinen.Add(new FamilyLinen { Name = "HAND BAND" });
            familyLinen.Add(new FamilyLinen { Name = "HAND MITTS" });
            familyLinen.Add(new FamilyLinen { Name = "HAND TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "HANDKERCHEIF" });
            familyLinen.Add(new FamilyLinen { Name = "HEAD BAND" });
            familyLinen.Add(new FamilyLinen { Name = "HEAD COVER" });
            familyLinen.Add(new FamilyLinen { Name = "HEAD FOAM" });
            familyLinen.Add(new FamilyLinen { Name = "HEAD REST" });
            familyLinen.Add(new FamilyLinen { Name = "HEAD SUPPORT" });
            familyLinen.Add(new FamilyLinen { Name = "HIP COVER" });
            familyLinen.Add(new FamilyLinen { Name = "HIP STRAP" });
            familyLinen.Add(new FamilyLinen { Name = "JACKET" });
            familyLinen.Add(new FamilyLinen { Name = "KAMIZ" });
            familyLinen.Add(new FamilyLinen { Name = "KANDURA" });
            familyLinen.Add(new FamilyLinen { Name = "KIMONO" });
            familyLinen.Add(new FamilyLinen { Name = "KNEE COVER" });
            familyLinen.Add(new FamilyLinen { Name = "KNEE PAD" });
            familyLinen.Add(new FamilyLinen { Name = "KURTA" });
            familyLinen.Add(new FamilyLinen { Name = "LEGGING" });
            familyLinen.Add(new FamilyLinen { Name = "LUNGI" });
            familyLinen.Add(new FamilyLinen { Name = "MAGAZINE HOLDER" });
            familyLinen.Add(new FamilyLinen { Name = "MASSAGE SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "MAT" });
            familyLinen.Add(new FamilyLinen { Name = "MATTRESSS" });
            familyLinen.Add(new FamilyLinen { Name = "MOLTEN" });
            familyLinen.Add(new FamilyLinen { Name = "MOP" });
            familyLinen.Add(new FamilyLinen { Name = "MOTON" });
            familyLinen.Add(new FamilyLinen { Name = "NAPKIN" });
            familyLinen.Add(new FamilyLinen { Name = "OUTERWEAR" });
            familyLinen.Add(new FamilyLinen { Name = "OVER LACE" });
            familyLinen.Add(new FamilyLinen { Name = "PAJAMA" });
            familyLinen.Add(new FamilyLinen { Name = "PANTIES" });
            familyLinen.Add(new FamilyLinen { Name = "PANTS" });
            familyLinen.Add(new FamilyLinen { Name = "PEDIATRIC TOY" });
            familyLinen.Add(new FamilyLinen { Name = "PILLOW" });
            familyLinen.Add(new FamilyLinen { Name = "PILLOW CASE" });
            familyLinen.Add(new FamilyLinen { Name = "POOL TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "PULLOVER" });
            familyLinen.Add(new FamilyLinen { Name = "RIBBON" });
            familyLinen.Add(new FamilyLinen { Name = "SALWAR" });
            familyLinen.Add(new FamilyLinen { Name = "SALWAR KAMIZ " });
            familyLinen.Add(new FamilyLinen { Name = "SAREE" });
            familyLinen.Add(new FamilyLinen { Name = "SCAF FOAM" });
            familyLinen.Add(new FamilyLinen { Name = "SCARF" });
            familyLinen.Add(new FamilyLinen { Name = "SEAT COVER" });
            familyLinen.Add(new FamilyLinen { Name = "SHAWL" });
            familyLinen.Add(new FamilyLinen { Name = "SHEILA" });
            familyLinen.Add(new FamilyLinen { Name = "SHIRT" });
            familyLinen.Add(new FamilyLinen { Name = "SHOES PAIR" });
            familyLinen.Add(new FamilyLinen { Name = "SHORT" });
            familyLinen.Add(new FamilyLinen { Name = "SIDE HEAD REST" });
            familyLinen.Add(new FamilyLinen { Name = "SIDE RAIL" });
            familyLinen.Add(new FamilyLinen { Name = "SIDE RAIL FOAM" });
            familyLinen.Add(new FamilyLinen { Name = "SKIRT" });
            familyLinen.Add(new FamilyLinen { Name = "SLACKS" });
            familyLinen.Add(new FamilyLinen { Name = "SLEEPING PLASTIC COVER" });
            familyLinen.Add(new FamilyLinen { Name = "SLEEVELESS" });
            familyLinen.Add(new FamilyLinen { Name = "SLIDING SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "SLIP" });
            familyLinen.Add(new FamilyLinen { Name = "SLIP/STOCKING" });
            familyLinen.Add(new FamilyLinen { Name = "SOCKS" });
            familyLinen.Add(new FamilyLinen { Name = "SOFA COVER " });
            familyLinen.Add(new FamilyLinen { Name = "SOFA PROTECTOR" });
            familyLinen.Add(new FamilyLinen { Name = "SPA FACE COVER" });
            familyLinen.Add(new FamilyLinen { Name = "SPA FACE CRADLE" });
            familyLinen.Add(new FamilyLinen { Name = "SPA MITTS" });
            familyLinen.Add(new FamilyLinen { Name = "SPANDEX" });
            familyLinen.Add(new FamilyLinen { Name = "SUIT" });
            familyLinen.Add(new FamilyLinen { Name = "SWEATER" });
            familyLinen.Add(new FamilyLinen { Name = "TABLE CLOTH" });
            familyLinen.Add(new FamilyLinen { Name = "TABLE COVER" });
            familyLinen.Add(new FamilyLinen { Name = "TABLE RUNNER" });
            familyLinen.Add(new FamilyLinen { Name = "TABLE SKIRTING" });
            familyLinen.Add(new FamilyLinen { Name = "TENT COVER" });
            familyLinen.Add(new FamilyLinen { Name = "TIE" });
            familyLinen.Add(new FamilyLinen { Name = "TOP SHEET" });
            familyLinen.Add(new FamilyLinen { Name = "TOWEL" });
            familyLinen.Add(new FamilyLinen { Name = "TOYS" });
            familyLinen.Add(new FamilyLinen { Name = "TRAY COVER " });
            familyLinen.Add(new FamilyLinen { Name = "TRAY LINER" });
            familyLinen.Add(new FamilyLinen { Name = "TROLLEY" });
            familyLinen.Add(new FamilyLinen { Name = "TROUSER" });
            familyLinen.Add(new FamilyLinen { Name = "T-SHIRT" });
            familyLinen.Add(new FamilyLinen { Name = "UMBRELLA" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERGARMENT" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERPANTS" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERSHIRT" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERSHORT" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERSLIP" });
            familyLinen.Add(new FamilyLinen { Name = "UNDERWEAR" });
            familyLinen.Add(new FamilyLinen { Name = "VEST" });
            familyLinen.Add(new FamilyLinen { Name = "WASH MITT" });
            familyLinen.Add(new FamilyLinen { Name = "WIPER PAD" });
            familyLinen.Add(new FamilyLinen { Name = "WOOL WEAR" });
        }

        private void AddMasterLinen(DataContext context)
        {
            var masterLinens = context.MasterLinens;

            //masterLinens.Add(new MasterLinen { Name = "Shirt", FamilyLinenId = 1, LinenTypeId = 1, GroupLinenId = 1 });

            masterLinens.Add(new MasterLinen { Name = "ABAYA", FamilyLinenId = 1, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ABAYA LARGE", FamilyLinenId = 1, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ABAYA MEDIUM", FamilyLinenId = 1, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ABAYA SMALL", FamilyLinenId = 1, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ABAYA YELLOW", FamilyLinenId = 1, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "APPLICATOR", FamilyLinenId = 2, LinenTypeId = 4, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GLASS APPLICATOR", FamilyLinenId = 2, LinenTypeId = 4, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WINDOW APPLICATOR", FamilyLinenId = 2, LinenTypeId = 4, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "APRON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "APRON BLACK", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "APRON SALOON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLAKC APRON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF APRON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COOK APRON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STEWARD APRON", FamilyLinenId = 3, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ARM REST", FamilyLinenId = 4, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BACK COVER", FamilyLinenId = 5, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BACK REST", FamilyLinenId = 6, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BACK REST COVER", FamilyLinenId = 6, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BACK SUPPORT", FamilyLinenId = 7, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BIN BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GARBAGE BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LAUNDRY BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLEEPING BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TOY BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "VACUUM BAG", FamilyLinenId = 8, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BANDANA", FamilyLinenId = 9, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH MAT", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH MAT WITH LOGO", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH MAT ", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH MAT BROWN", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH MAT CREAM", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH MAT WHITE", FamilyLinenId = 10, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BATH ROBE", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH ROBE", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH ROBE BELT", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH ROBE CREAM", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH ROBE GREEN", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH ROBE WAFFLE/TERRY", FamilyLinenId = 11, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH RUG", FamilyLinenId = 12, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH RUG", FamilyLinenId = 12, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH SHEET ", FamilyLinenId = 13, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH SHEET", FamilyLinenId = 13, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH TOWEL", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH TOWEL BROWN", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH TOWEL CREAM", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH TOWEL WITH BLUE LINE", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BATH TOWEL XL", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BIG BATH TOWEL", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GYM BATH TOWEL", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH TOWEL", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH TOWEL BLUE", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH TOWEL BROWN", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH TOWEL CREAM", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BATH TOWEL GREEN", FamilyLinenId = 14, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED PROTECTOR", FamilyLinenId = 15, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SKIRTING", FamilyLinenId = 15, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SKIRTING KING", FamilyLinenId = 15, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SKIRTING SINGLE", FamilyLinenId = 15, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED  PROTECTOR", FamilyLinenId = 15, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BED COVER", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED COVER", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED COVER GREEN", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL BED COVER", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BED COVER", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SUN BED COVER", FamilyLinenId = 16, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BED LINER", FamilyLinenId = 17, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED LINER", FamilyLinenId = 17, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED RUNNER", FamilyLinenId = 18, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BED SHEET", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET COVER", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET CREAM", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET KING", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET KING DOUBLE", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET QUEEN", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET SINGLE", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET TOP KING", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET TOP TWIN", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET TWIN", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BED SHEET", FamilyLinenId = 19, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SPREAD", FamilyLinenId = 20, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED THROW ", FamilyLinenId = 21, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BEDDING FEATHER KING", FamilyLinenId = 22, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BROWN BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEST BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HIP BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KIMONO BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RED BELT", FamilyLinenId = 23, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BIDET TOWEL", FamilyLinenId = 24, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BLANKET", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET ALL SIZE", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET COVER", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET DOUBLE", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET KING", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLANKET SINGLE", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BLANKET", FamilyLinenId = 25, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY BLOUSE", FamilyLinenId = 26, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLOUSE", FamilyLinenId = 26, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET BOTTOM KING", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SHEET BOTTOM TWIN", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KING BOTTOM SHEET YELLOW ST.", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "QUEEN BOTTOM SHEET WITH BLUE ST.", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SINGLE BOTTOM SHEET PLAIN COVER", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TWIN BOTTOM SHEET RED ST.", FamilyLinenId = 27, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BOW TIE", FamilyLinenId = 28, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BRASSIERE", FamilyLinenId = 29, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BREAD BASKET", FamilyLinenId = 30, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BREAD COVER", FamilyLinenId = 31, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ARABIC CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COOK CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAIR CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STEWARD CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STRIPE CAP", FamilyLinenId = 32, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CARPET", FamilyLinenId = 33, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CARPET PER PC", FamilyLinenId = 33, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CARPET PER SQUARE METER", FamilyLinenId = 33, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR COVER", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR COVER BROWN", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR COVER DOUBLE", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR COVER SINGLE", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR COVER STRETCH", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR RIBBON", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHAIR RIBBON COLOUR", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL CHAIR COVER", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WHEAT CHAIR COVER", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WHEEL CHAIR PADS", FamilyLinenId = 34, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEST COVER", FamilyLinenId = 35, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEST SUPPORT", FamilyLinenId = 36, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FABRIC CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FEATHER CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GLASS CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KITCHEN CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LEATHER CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MICRO FIBER CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP MICRO FIBER CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RAMADAN CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SATIN CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SATIN CLOTH BIG", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SATIN CLOTH SMALL", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY CLOTH ROOM SERVICE ", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WIPING CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WOVAN CLOTH", FamilyLinenId = 37, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COASTER", FamilyLinenId = 38, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COVER COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DOCTOR'S COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EMBROIDERED LONG WAIST COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LAB COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "OVER COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "VEST COAT", FamilyLinenId = 39, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COMFORTER", FamilyLinenId = 40, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COMFORTER COVER", FamilyLinenId = 40, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COSTUME", FamilyLinenId = 41, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY COVERALL", FamilyLinenId = 42, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COVERALL", FamilyLinenId = 42, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN HEAVY BLACK OUT LARGE PER PC.", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN HEAVY BLACK OUT SMALL PER PC.", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN INNER", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAVY CURTAIN", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAVY CURTAIN PER PC.", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LIGHT CURTAIN", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHEER CURTAIN", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHEER CURTAINS", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHOWER CURTAIN PER PC.", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA CURTAIN", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WINDOW CURTAINS", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN SKIRTING", FamilyLinenId = 43, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION  ", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION COVER", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION COVER ALL SIZES", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION COVER LARGE", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION COVER MEDIUM", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CUSHION COVER SMALL ", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SOFA CUSHION WITH COVER", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA CUSHION WITH COVER", FamilyLinenId = 44, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY DRESS", FamilyLinenId = 45, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DRESS", FamilyLinenId = 45, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DRESS BELT", FamilyLinenId = 45, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NIGHT DRESS", FamilyLinenId = 45, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PRAYER DRESS", FamilyLinenId = 45, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF'S DUSTER", FamilyLinenId = 46, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUSTER", FamilyLinenId = 46, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUSTER COLOUR", FamilyLinenId = 46, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY DUVET", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET ALL SIZE", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET FEATHER KING", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET KING", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET PROTECTOR", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET SINGLE", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET TWIN", FamilyLinenId = 47, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY DUVET COVER", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER KING", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER QUEEN", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER SINGLE", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER TOP KING", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DUVET COVER TWIN", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA DUVET COVER", FamilyLinenId = 48, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EQUIPMENT COVER", FamilyLinenId = 49, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FACE MASK", FamilyLinenId = 50, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FACE TOWEL", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FACE TOWEL BLUE", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FACE TOWEL BROWN", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FACE TOWEL CREAM", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA BROWN FACE TOWEL", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FACE TOWEL", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FACE TOWEL BLUE", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FACE TOWEL CREAM", FamilyLinenId = 51, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY FITTED SHEET", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FITTED SHEET KING", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FITTED SHEET TWIN", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FITTED SHEET/FLAT SHEET", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FITTED SHEET", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FITTED SHEET COVER ", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FITTED SHEET COVER CREAM", FamilyLinenId = 52, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FLAG", FamilyLinenId = 53, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FLAG STITCHING AND WASHING", FamilyLinenId = 53, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FLAT LINENS", FamilyLinenId = 54, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FOAM BACK", FamilyLinenId = 55, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FOAM COVER", FamilyLinenId = 56, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FOOT COVER", FamilyLinenId = 57, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FOOT SUPPORTER", FamilyLinenId = 58, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FWALA COVER", FamilyLinenId = 59, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GLASS BRUSH", FamilyLinenId = 60, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GLOVES", FamilyLinenId = 61, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND GLOVES", FamilyLinenId = 61, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ADULT PATIENT GOWN", FamilyLinenId = 62, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NIGTH GOWN", FamilyLinenId = 62, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PRAYER GOWN", FamilyLinenId = 62, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GUTRA", FamilyLinenId = 63, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GUTRA & KHAFIA", FamilyLinenId = 64, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND BAND", FamilyLinenId = 65, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND MITTS", FamilyLinenId = 66, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GYM HAND TOWEL", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND TOWEL", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND TOWEL BLUE", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND TOWEL BROWN", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND TOWEL CREAM", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HAND TOWEL GRAY", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SALOON HAND TOWEL", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND TOWEL", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND TOWEL BLUE", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND TOWEL BROWN", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND TOWEL CREAM", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA HAND TOWEL WHITE", FamilyLinenId = 67, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HANDKERCHEIF", FamilyLinenId = 68, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAD BAND", FamilyLinenId = 69, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAD COVER", FamilyLinenId = 70, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA  HEAD COVER", FamilyLinenId = 70, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAD FOAM", FamilyLinenId = 71, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAD REST", FamilyLinenId = 72, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HEAD SUPPORT", FamilyLinenId = 73, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HIP COVER", FamilyLinenId = 74, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HIP STRAP", FamilyLinenId = 75, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF'S JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COOK JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DOCTOR'S COAT OR JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EXECUTIVE JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STEWARD JACKET", FamilyLinenId = 76, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KAMIZ", FamilyLinenId = 77, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KANDURA", FamilyLinenId = 78, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KIMONO", FamilyLinenId = 79, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KNEE COVER", FamilyLinenId = 80, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KNEE PAD", FamilyLinenId = 81, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KURTA", FamilyLinenId = 82, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LEGGING", FamilyLinenId = 83, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LUNGI", FamilyLinenId = 84, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MAGAZINE HOLDER", FamilyLinenId = 85, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MASSAGE SHEET", FamilyLinenId = 86, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BED SIDE MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DOOR MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FOOT MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "LATEX MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MAT PROTECTOR", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PLACE MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PLACE MAT COLORED", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PLACE MAT CREAM", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PLACE MAT ORANGE", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PLACE MAT RED", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PRAYER MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA DOORMAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FOOT MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA MAT RASH COVER", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY MAT COLORED", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY MAT ROUND", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY MAT WHITE", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TURN DOWN MAT", FamilyLinenId = 87, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY MATTRESS", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY MATTRESS COVER", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY MATTRESS PAD", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS COVER", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS KING", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PAD KING", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PAD PROTECTOR KING", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PAD PROTECTOR SINGLE", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PAD SINGLE", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PROTECTOR", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PROTECTOR KING", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS PROTECTOR TWIN", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS SINGLE", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MATTRESS TOPPER KING", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA MATTRESS COVER", FamilyLinenId = 88, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOLTEN", FamilyLinenId = 89, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP BLUE", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP HEAD", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP LACE", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP WET/DRY", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP WHITE", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOP WINDOW/GLASS", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PUSH MOP", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WET MOP", FamilyLinenId = 90, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "MOTON", FamilyLinenId = 91, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BANQUET WHITE NAPKIN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CRISTAL COCKTAIL NAPKIN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN ANGAR", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN BALCK", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN BLUE", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN BOX", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN BROWN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN BURGUNDY", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN CATALAN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN CHAMPANGE", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN COCKTAIL", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN COLOUR", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN CREAM", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN FLOWER", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN GOLD", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN GRAY", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN GREY", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN KAZU", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN RED", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN ROOM SERVICE", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "NAPKIN TOILET", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE NAPKIN", FamilyLinenId = 92, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "OUTERWEAR", FamilyLinenId = 93, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "OVER LACE", FamilyLinenId = 94, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY PAJAMA", FamilyLinenId = 95, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KURTA PAJAMA", FamilyLinenId = 95, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PAJAMA", FamilyLinenId = 95, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PANTIES", FamilyLinenId = 96, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY PANTS", FamilyLinenId = 97, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "JOGGING PANTS", FamilyLinenId = 97, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PANTS", FamilyLinenId = 97, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PEDIATRIC TOY", FamilyLinenId = 98, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY PILLOW", FamilyLinenId = 99, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW", FamilyLinenId = 99, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW KING", FamilyLinenId = 99, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW PEDIATRIC", FamilyLinenId = 99, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "THROW PILLOW", FamilyLinenId = 99, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY PILLOW CASE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE BACK KING", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE BACK QUEEN", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE CABANA", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE COLORED", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE EMBROIDERY KING", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE EMBROIDERY QUEEN", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE FRONT KING", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE FRONT QUEEN", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE KING", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE TWIN", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE WHITE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW CASE WITH BORDER", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW COVER", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW PROTECTOR", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PILLOW SLIP", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA PILLOW CASE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPECIAL PILLOW COVER", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SUNBED PILLOW CASE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "THROW PILLOW CASE", FamilyLinenId = 100, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL BLUE DARK", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL BROWN", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL CREAM", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL KING SIZE", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL WHITE", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL TOWEL WITH BLUE LINE", FamilyLinenId = 101, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY PULLOVER", FamilyLinenId = 102, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PULLOVER", FamilyLinenId = 102, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RIBBON", FamilyLinenId = 103, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SALWAR", FamilyLinenId = 104, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SALWAR KAMIZ", FamilyLinenId = 105, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SAREE", FamilyLinenId = 106, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SCAF FOAM", FamilyLinenId = 107, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SCARF", FamilyLinenId = 108, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SEAT COVER", FamilyLinenId = 109, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHAWL", FamilyLinenId = 110, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHEILA", FamilyLinenId = 111, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF SHIRT BLACK", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF SHIRT WHITE", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DOCTOR'S SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ENGINEERING SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EXECUTIVE SHIRTS", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "F&B SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FO SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HK SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STEWARDING SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WAITERS SHIRT", FamilyLinenId = 112, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHOES PAIR", FamilyLinenId = 113, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SHORT", FamilyLinenId = 114, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL SHORT", FamilyLinenId = 114, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SHORT", FamilyLinenId = 114, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SIDE HEAD REST", FamilyLinenId = 115, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SIDE RAIL", FamilyLinenId = 116, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SIDE RAIL FOAM", FamilyLinenId = 117, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SKIRT", FamilyLinenId = 118, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SKIRT", FamilyLinenId = 118, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLACKS", FamilyLinenId = 119, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLEEPING PLASTIC COVER", FamilyLinenId = 120, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLEEVELESS", FamilyLinenId = 121, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLIDING SHEET", FamilyLinenId = 122, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SLIP", FamilyLinenId = 123, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLIP", FamilyLinenId = 123, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SLIP/STOCKING", FamilyLinenId = 124, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SOCKS", FamilyLinenId = 125, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SOCKS", FamilyLinenId = 125, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SOFA COVER ", FamilyLinenId = 126, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SOFA COVER LARGE", FamilyLinenId = 126, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SOFA PROTECTOR", FamilyLinenId = 127, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FACE COVER", FamilyLinenId = 128, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA FACE CRADLE", FamilyLinenId = 129, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA MITTS", FamilyLinenId = 130, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPANDEX", FamilyLinenId = 131, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SAFARI SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA SUIT TOP", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SUIT 2 PCS", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SUIT 3 PCS", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SWIM SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRACK SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WAITER BLACK SUIT", FamilyLinenId = 132, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY SWEATER", FamilyLinenId = 133, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SWEATER", FamilyLinenId = 133, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COCKTAIL TABLE CLOTH", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RAMADAN TABLE CLOTH ", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 100 X 100", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 100 X 150", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 120 X 290", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 145 X 170", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 160 X 160", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 160 X 210", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 180X180", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH 240 X 240", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ALL SIZES", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH BLACK", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH BLUE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH CREAM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH GOLD", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH MARBLE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH RECTANGLE LARGE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH RECTANGLE MEDIUM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH RECTANGLE SMALL", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH RED", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROOM SERVICE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROOM SERVICE BROWN", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROOM SERVICE WHITE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 150", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 170", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 200", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 225", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 260", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 270", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND 400", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND ALL SIZES", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND BLACK", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND CREAM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND EXTRA LARGE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND GREY LINE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND LARGE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND MEDIUM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND OVERLAY ", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH ROUND SMALL", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH RUST", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH SILKY", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH SKIRTING", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH SQUARE LARGE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH SQUARE MEDIUM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH SQUARE SMALL", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH STRETCH", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH UNDER LAY LARGE", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH UNDER LAY MEDIUM", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH UNDERLAY ", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH VELVET", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE CLOTH YELLOW", FamilyLinenId = 134, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COCKTAIL TABLE COVER BLACK", FamilyLinenId = 135, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COCKTAIL TABLE COVER WHITE", FamilyLinenId = 135, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE COVER", FamilyLinenId = 135, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE COVER BLACK", FamilyLinenId = 135, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE COVER BLACK CLASS", FamilyLinenId = 135, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE RUNNER", FamilyLinenId = 136, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE RUNNER  RED", FamilyLinenId = 136, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE RUNNER ORANGE", FamilyLinenId = 136, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE SKIRTING", FamilyLinenId = 137, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TABLE SKIRTING GREEN", FamilyLinenId = 137, LinenTypeId = 2, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TENT COVER", FamilyLinenId = 138, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF'S TIE ", FamilyLinenId = 139, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COOK TIE", FamilyLinenId = 139, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CURTAIN TIE", FamilyLinenId = 139, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TIE", FamilyLinenId = 139, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KING TOP SHEET YELLOW TAG", FamilyLinenId = 140, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "QUEEN TOP SHEET BLUE TAG", FamilyLinenId = 140, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SINGLE TOP SHEET PLAIN COVER", FamilyLinenId = 140, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TWIN TOP SHEET RED TAG", FamilyLinenId = 140, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BROWN TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EYE TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "GYM TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "KITCHEN TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RECREATION PURPLE TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "RECREATION SUN BED TOWEL ", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA JUMBO TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA TOWEL ", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA TURKISH TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STAFF TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TOWEL", FamilyLinenId = 141, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TOYS", FamilyLinenId = 142, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY COVER ", FamilyLinenId = 143, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TRAY LINER", FamilyLinenId = 144, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TROLLEY BAG", FamilyLinenId = 145, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TROLLEY COVER", FamilyLinenId = 145, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BLACK TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BROWN TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "CHEF TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "COOK TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "DOCTOR'S TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "ENGINEERING TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "EXECUTIVE TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FO TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "PATIENT GOWN TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "SPA SUITE TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "STEWARDING TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "TROUSER", FamilyLinenId = 146, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY T-SHIRT", FamilyLinenId = 147, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "FO T-SHIRT", FamilyLinenId = 147, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "HK T-SHIRT", FamilyLinenId = 147, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "POOL T-SHIRT", FamilyLinenId = 147, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "T-SHIRT", FamilyLinenId = 147, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UMBRELLA COVER", FamilyLinenId = 148, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERGARMENT", FamilyLinenId = 149, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY UNDERPANTS", FamilyLinenId = 150, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERPANTS", FamilyLinenId = 150, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY UNDERSHIRT", FamilyLinenId = 151, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERSHIRT", FamilyLinenId = 151, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY UNDERSHORT", FamilyLinenId = 152, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERSHORT", FamilyLinenId = 152, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERSLIP", FamilyLinenId = 153, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "BABY UNDERWEAR", FamilyLinenId = 154, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "UNDERWEAR", FamilyLinenId = 154, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "VEST", FamilyLinenId = 155, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WAISTCOAT", FamilyLinenId = 155, LinenTypeId = 3, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WASH MITT", FamilyLinenId = 156, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WIPER PAD", FamilyLinenId = 157, LinenTypeId = 1, GroupLinenId = 1 });
            masterLinens.Add(new MasterLinen { Name = "WOOL WEAR", FamilyLinenId = 158, LinenTypeId = 1, GroupLinenId = 1 });

        }

        private void AddPrimeInfo(DataContext contex)
        {
            var primeInfo = contex.PrimeInfos;

            primeInfo.Add(new PrimeInfo
            {
                Name = "PRIME AUTOMATIC LAUNDRY",
                Address = "91502, Street No.16, Mussafah 36, Abu Dhabi",
                TRNNumber = "Rahim What is TRN #?",
                VAT = 0.05,
            });
        }

    }
}